# Generated by Django 6.0.2 on 2026-02-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('rider', 'Rider'), ('admin', 'Admin')], default='customer', max_length=50),
        ),
    ]
